# Generated by Django 5.2 on 2025-09-19 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
